### ISSUE TITLE
Will there be a mac dev environment available?

### ISSUE THREAD

**Issue by cynx** [Microsoft/HoloJS#12]
Any plans to allow development on mac os Sierra?

**Comment by IvRRimum** [comment]
Tryed this on virtualbox Windows 10( i am running Sierra on my base too ). Works fine like that.

**Comment by Almost-Done** [comment]
You could configure the host UWP to run the scripts from the web instead of from he local package. See RunWebScriptAppAsync.

Development on the scripted side is basically web development. You create WebGL scripts in your favorite environment, publish them to the web and launch the app on the HoloLens to download and execute them. Scripts should render in a browser as is using a view and projection matrix. You can detect when running on the HoloLens by the presence of window.experimentalHolographic and in that case use an identity projection matrix and the provided view matrix - like in the sample - to world lock your content.

**Comment by Almost-Done** [comment]
There are no plans to enable building the native host code on Mac OS. You need Visual Studio for that task, so Parallels or BootCamp will be required.
