### ISSUE TITLE
Support for Three js is missing

### ISSUE THREAD

**Issue by dbs2000** [Microsoft/HoloJS#16]
Do you guys have any plans of bringing in support for three js? If so then it will be great for developers. There is a very similar impelmentation in gitgub called HolographicJS (https://github.com/lwansbrough/HolographicJS) just like yours. That seems to have support for three.js.
If you don't have plans then can you please guide me on how to include it? I have few implementations in three.js that I would like to bring into hololens. Thanks

**Comment by lwansbrough** [comment]
@dbs2000 My library actually doesn't support Three.js.

Here are a few of the issues I've experienced so far in trying to support it:

- Three.js defines a `transpose` method in one of its shaders which is already defined in OpenGL ES I guess? Removing the offending function seems to solve that problem temporarily, but there needs to be a better solution obviously. We can't be monkey-patching Three.js.

```
ERROR: 0:98: 'const' : overloaded functions must have the same parameter qualifiers 
ERROR: 0:98: 'transpose' : built-in functions cannot be redefined 
```

- https://github.com/Microsoft/HoloJS/issues/18
- https://github.com/Microsoft/HoloJS/issues/17
- App.cpp in the sample app sets the OpenGL ES version to 3.0, however only WebGL 2.0 is a derivation of OpenGL ES 3.0, not WebGL 1.0

**Comment by dbs2000** [comment]
@lwansbrough Thanks for your reply. So what do you think should be my next step? Rewrite my existing implementations, that are in three.js, in WebGL as required by holo.js, or wait for three js support to come?

**Comment by lwansbrough** [comment]
@dbs2000 Unless your apps are very basic, I would strongly recommend against coding directly in WebGL. I'd say wait for Three.js support, or help make it a reality. :)

**Comment by dbs2000** [comment]
@lwansbrough Thanks...

**Comment by j6k4m8** [comment]
Obviously there's a ton of support for an idea like this. Is there a recommended or requested place for devs like myself to get involved and help get this in motion?

**Comment by lwansbrough** [comment]
@j6k4m8 I'd say if you're interested, load an app with Three.js and start tracking down the errors one by one. I'm sure the authors would be happy to accept small PRs the address minor incompatibilities. Check out the issues I've created to get a head start.

**Comment by centigradeclemensP** [comment]
Wow, thanks, that is good news. ThreeJS performs extremely well with Angular 2 and Electron which makes it a lightweight yet powerful tool for deploying 3D to Classic Desktop, Web, Mobile and even VR. It would be perfect to be able to use it for the HoloLens as well. But having BabylonJS support will be excellent too, so I am really looking forward to it. Thanks for working on this.

**Comment by sjando** [comment]
I've been playing with this a bit and managed to get Three.js up and running (https://github.com/sjando/HoloJS/tree/three.js). There's a couple of notable limitations, namely only one shader can be in use at a time and frustum culling must be turned off. But in general things work as expected so far as I've tried. Noticed a couple of the required changes have been implemented here in the last day or so, maybe I'll tidy things up and submit a PR with the others.

**Comment by Almost-Done** [comment]
@sjando Thank you so much for getting Three.js to work! Please submit a PR; this will make a lot of people happy.

The single shader issue is known and we're working on getting it fixed. We discovered it while getting Babylon.js to work. Since we don't have an official issue filed, would you mind opening one?

The culling issue was encountered in Babylon.js as well. We fixed it by having Babylon's holographic camera provide its view frustum to Babylon engine for proper culling. Babylon had a mechanism for doing this; I'm not sure how this could be done in Three.js.

**Comment by centigradeclemensP** [comment]
@sjando Thanks a lot, this came faster than I dared to hope! I am happy. I will try to port a project I am working on and report if I find any additional issues.

**Comment by sjando** [comment]
@Almost-Done I'm not sure how the culling issue should be solved. Three.js computes the view frustum for culling based on the projection matrix supplied by the camera. Problem is, this same projection matrix will then also be used in the shader pipeline, so it has to be given as identity in order to work with ANGLE's automatic projection.

It might be possible to make a plugin for Three's renderer that allows frustum culling to work as expected but then prevents/undoes the projection transform ready for ANGLE, but I haven't looked into this yet. In any case, solving the multi-shader issue may well require some changes to the way automatic stereo/projection works, so it might be better to get that working first.

**Comment by andybeaulieu** [comment]
Is BabylonJS support still a work-in-progress then?  @Almost-Done mentioned fixing some issues with it above, but I'm not able to get a simple sample working.

**Comment by arondesign** [comment]
+1, @Almost-Done is there a Babylon.js example somewhere?

**Comment by Almost-Done** [comment]
Sorry, babylon.js support is not ready and there is no sample yet. Before releasing it, we want to solve the multiple shader issue. There is a ThreeJS sample now that works with known issues.

**Comment by Almost-Done** [comment]
Many thanks to @sjando for making the required fixes to HoloJS to get ThreeJS running and creating a ThreeJS sample app. I will close this issue and open smaller items for the remaining known issues.
