### ISSUE TITLE
OpenGL and EGL includes are not found when trying to build the solution. 

### ISSUE THREAD

**Issue by whohlfeld** [Microsoft/HoloJS#165]
![2018-05-11 10_30_34-holojs-vs2017 - microsoft visual studio](https://user-images.githubusercontent.com/33004991/39914855-8c086200-5506-11e8-9762-8ee7432d90fd.png)

When trying to build the solution for the first time, VS thows the errors that the source files for the includes cannot be opened. Stackoverflow only has a solution for this issue with Qt which does not work for me on this project.

**Comment by omaralcheikh** [comment]
Make sure you downloaded angle and copied the contents inside the angle folder

![image](https://user-images.githubusercontent.com/4421054/39919509-813dd272-551c-11e8-8ff9-553fee9b7383.png)

**Comment by Almost-Done** [comment]
Those headers come from the ANGLE submodule.
There was an issue with the ANGLE submodule and it was not cloning properly due to a bad commit ID. I pushed a fix to master.

1. Pull the latest master.
2. Make sure you cloned: the ANGLE submodule
If you already cloned HoloJS, run this git command from the repo: "git submodule update --init --recursive"
If you did not clone HoloJS, do it recursively: git clone --recursive ...

**Comment by whohlfeld** [comment]
Thanks a lot, that solved the issue! But I still had to copy teh ANGLE folder manually.
