### ISSUE TITLE
Windows Universal Runtime version 10.0.16299.0 

### ISSUE THREAD

**Issue by Dasan** [Microsoft/HoloJS#170]
I guess the current HoloJS supports Windows Universal Runtime version 10.0.16299.0 but Hololens emulator (actual Hololens, too) is running version 10.0.14393.1358. So I cannot run the examples on Hololens emulator, because there is no Hololens emulator 10.0.16299.0.  I didn't test actual Hololens yet but it is also based on 10.0.14393.1358. Is there any way to solve this issue?

If I try to run example HoloJS apps, I face this error message:

_Error		DEP3321: To deploy this application, your deployment target should be running Windows Universal Runtime version 10.0.16299.0 or higher. You currently are running version 10.0.14393.1358. Please update your OS, or change your deployment target to a device with the appropriate version.	HoloJsWebViewer-Vs2017_

**Comment by Almost-Done** [comment]
HoloJS requires RS3 (16299). While you are right in that HoloLens did not get 16299, an even newer version 17134 is available for HoloLens.

The latest emulator version is 10.0.17134.80. See this link: [HoloLens emulator archive](https://docs.microsoft.com/en-us/windows/mixed-reality/hololens-emulator-archive)

The latest HoloLens release is 10.0.17134.80 as well. See [Mixed Reality Release Notes](https://docs.microsoft.com/en-us/windows/mixed-reality/release-notes)

HoloJS should work on these new versions. Please let me know if you are experiencing otherwise.
