### ISSUE TITLE
SpatialInput issue on any hand gesture

### ISSUE THREAD

**Issue by Reda-S** [Microsoft/HoloJS#39]
Once I start any hand gesture, the “SpatialInput.cpp” is logging an error on the output window:
Failure in file ..spatialinput.cpp, line 82 

Line # 82 of spatialinput is: “EXIT_IF_JS_ERROR(JsDoubleToNumber(x, xParam));” 

This prevent the JavaScript callback function to be called back.
When I check the returned “JsErrorCode” : it is “JsErrorNoCurrentContext”, so the context has been lost somehow. 

The HoloLens OS that I am using is: 10.0.14393.1198

**Comment by Almost-Done** [comment]
The JS runtime context is bound to the UI thread.  In RS1, the SpatialInteractionManager invokes input callbacks on random threads, not the thread where the registration occurred. Calling JS functions on non-UI threads fails with "no context" since those threads do not have a JS runtime context.

In RS2, SpatialInteractionManager invokes callbacks on the same thread where registration occurred.

The fix is to explicitly request "same thread execution context" for callbacks.

**Comment by IL55** [comment]
Thanks for JS support for hololens!

I want to say that I checkout branch `develop/fix-task-continuation-thread` from PR #40 
And it seems that problem still here. I setup breakpoint and see that only first parameter (m_scriptCallback) has valid pointer but others 7 are 0xcccccccc.

**Comment by Almost-Done** [comment]
@IL55 On the develop/fix-task-continuation-thread branch, do you get spatial input events in the script? Or do you still see errors from file spatialinput.cpp?

**Comment by IL55** [comment]
I've added console.log and see that events arrive to script OK. So no any problem? Just rotation of the cube is not so visible ?

**Comment by Almost-Done** [comment]
In the ThreeJS sample, if you tap and hold then move your hand left or right, the cube should rotate. The cube does not rotate much, you can amplify the rotation by changing the script.

**Comment by Almost-Done** [comment]
This should be now fixed, including the slow delivery of hand updates.
