### ISSUE TITLE
HoloOpenGLES.Net?

### ISSUE THREAD

**Issue by JimSEOW** [Microsoft/HoloJS#57]
Could Microsoft support OpenGLES for C# in mixed reality (HoloLens)
Currently, I am starting this by [porting C++ OpenGLES XAML template to C#](https://github.com/Microsoft/angle/issues/125#issuecomment-314017594)
It would be great if I could get support for doing this.

With support, we could port these [Angle Holographics C++ UWP templates](https://github.com/Microsoft/angle/tree/ms-holographic-experimental/templates/10/Windows/Universal) to C# community who prefer NON-Unity3D approach.

**Comment by Almost-Done** [comment]
I would think that it's easier and more efficient to use DirectX instead of OpenGLES.

Consider that OpenGLES with ANGLE is ultimately implemented in DirectX, so your stack really is: C# -> OpenGLES -> ANGLE -> DirectX. Instead you can go C# -> DirectX directly.

Maybe this link will help: [https://msdn.microsoft.com/en-us/library/windows/desktop/bb153298(v=vs.85).aspx](url)

**Comment by JimSEOW** [comment]
@Almost-Done
 I am aware of SharpDX UWP XAML interop for C#. 

UWP is a great vision. Unfortunately for users coming from OpenTK (e.g WPF/C#), without Angle.WindowStore for C#, there is no continuous path towards UWP.

**Comment by Almost-Done** [comment]
Could you take OpenTK and change its OpenGL imports to come from ANGLE instead of the system's OpenGL binaries? Then you'd run OpenTK on top of Angle.WindowStore and it might work.

This is not a direction for this project though. HoloJS is about scripting for mixed reality and bridging web and HoloLens development.
